//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDACTP034150.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DDACEntities7 : DbContext
    {
        public DDACEntities7()
            : base("name=DDACEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<CargoBooking> CargoBookings { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Shiptransaction> Shiptransactions { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
